language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Ru1x1nYu"
  - git config user.email "875994852@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${blog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - resource
env:
 global:
   - GH_REF: github.com/Ru1x1nYu/Ru1x1nYu.github.io.git